import { useEffect, useState } from 'react';
import { supabase, isSupabaseConfigured } from '../lib/supabase';

export default function VideoQuiz({ videoId }) {
  const [questions, setQuestions] = useState([]), [answers, setAnswers] = useState({}), [started, setStarted] = useState(false), [result, setResult] = useState(null), [busy, setBusy] = useState(false);
  useEffect(() => { setQuestions([]); setAnswers({}); setStarted(false); setResult(null); if (isSupabaseConfigured && supabase && videoId) supabase.rpc('get_video_quiz', { p_video_id: videoId }).then(({ data }) => setQuestions(data || [])); }, [videoId]);
  if (!questions.length) return null;
  const submit = async () => { if (Object.keys(answers).length !== questions.length) return; setBusy(true); const { data, error } = await supabase.rpc('submit_video_quiz', { p_video_id: videoId, p_answers: answers }); setBusy(false); if (!error && data?.[0]) setResult(data[0]); };
  return <section className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4"><div className="flex flex-wrap justify-between gap-3 items-center"><div><h3 className="font-bold text-white">理解度チェック</h3><p className="text-xs text-slate-400 mt-1">何度でも挑戦できます。</p></div>{!started && <button type="button" onClick={() => setStarted(true)} className="px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 font-bold text-xs">挑戦する（{questions.length}問）</button>}</div>{result && <div className="rounded-xl bg-emerald-500/10 border border-emerald-400/30 p-4 text-sm text-emerald-200">今回: <b>{result.score} / {result.total_questions}点</b>　最高点: <b>{result.best_score}点</b><button type="button" onClick={() => { setAnswers({}); setResult(null); }} className="ml-3 underline">もう一度挑戦</button></div>}{started && !result && <div className="space-y-5">{questions.map((q, i) => <fieldset key={q.id} className="border-t border-slate-800 pt-4"><legend className="text-sm font-semibold text-white">{i + 1}. {q.question_text}</legend><div className="mt-3 grid gap-2">{(q.options || []).map((option, n) => <label key={n} className={`cursor-pointer rounded-xl border p-3 text-xs ${answers[q.id] === n + 1 ? 'border-cyan-400 bg-cyan-400/10 text-cyan-100' : 'border-slate-700 text-slate-300'}`}><input className="sr-only" type="radio" name={q.id} checked={answers[q.id] === n + 1} onChange={() => setAnswers({ ...answers, [q.id]: n + 1 })} />{n + 1}. {option}</label>)}</div></fieldset>)}<button type="button" disabled={busy || Object.keys(answers).length !== questions.length} onClick={submit} className="w-full rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 py-3 text-sm font-bold text-white disabled:opacity-50">{busy ? '採点中…' : '回答を送信して採点'}</button></div>}</section>;
}
