import Link from "next/link";
import Head from "next/head";

export default function FirstPost() {
  return (
    <>
      {/* Head は最初に配置 */}
      <Head>
        <title>Total rapid blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/kohacu.com_samune_003505.png" />
      </Head>
      {/* 親要素で全体をラップ */}
      <div>
        <h1>First Post</h1>
        <h2>
          <Link href="/">Home</Link>
        </h2>
      </div>
    </>
  );
}
