import Head from 'next/head';
import Image from 'next/image';
import dynamic from 'next/dynamic';
import styles from '../src/styles/miyazaki-online.module.css';

const LINE_URL = 'https://lin.ee/Nwh2C8u';
function IconLine() { return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 4C6.9 4 3 7.3 3 11.4c0 3.6 3.1 6.6 7.4 7.2-.3 1-.2 1.9-.1 2.5.1.4.4.5.7.3.5-.3 2.4-1.6 3.6-2.6 5-.4 8.4-3.5 8.4-7.4C23 7.3 17.1 4 12 4z" fill="currentColor" /></svg>; }
function CheckIcon() { return <svg className={styles.checkIcon} width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="2" /><path d="m8 12 2.5 2.5L16 9" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function StepIcon({ step }) { const paths = { '01': <><rect x="5" y="4" width="14" height="16" rx="2" /><path d="M8 8h8M8 12h5M8 16h8" /></>, '02': <><circle cx="10" cy="10" r="5" /><path d="m14 14 5 5M8 10h4M10 8v4" /></>, '03': <><path d="M5 5h14v10H5z" /><path d="M9 20h6M12 15v5" /></>, '04': <><path d="M6 5h12v14H6z" /><path d="m9 12 2 2 4-5" /></> }; return <svg className={styles.stepIcon} viewBox="0 0 24 24" fill="none" aria-hidden="true">{paths[step]}</svg>; }
function LineCta({ children = '初回指導について相談する' }) { return <a className={styles.cta} href={LINE_URL} target="_blank" rel="noopener noreferrer"><IconLine />{children}</a>; }

const pillars = [['01', '人', '塾長が直接指導', '誰に教わるかが、最初から決まっています。'], ['02', '戦略', '宮崎県特化の個別最適化', '宮崎県を知るから、遠回りさせない。'], ['03', '仕組み', '単発指導 × アーカイブ', '単発なのに、学びが残る。']];
const scenes = ['テスト前だけ相談したい', '苦手単元だけ克服したい', '学校のワークが分からない', '高校受験前に対策したい', '普段は自分で勉強したい', '単発の問題を解決したい'];
const worries = [
  '学校のワークでどうしても解けない問題がある',
  '定期テスト前だけ、集中して質問できる先生がほしい',
  '苦手な単元だけを短期間でピンポイント克服したい',
  '塾に毎週通うほどではないけれど、独学だけでは不安',
  '高校受験直前に追加で難問対策や相談をしたい',
  '毎回担当が変わる一般的な個別指導塾に馴染めない',
];
const flowSteps = [['01', '教えてほしい内容を送る', '前日までに教材・問題・苦手な内容をLINEで送信。'], ['02', '塾長が内容を確認', '教材と質問内容を読み込み、必要な授業を準備。'], ['03', '50分の個別指導', '前半は講義、後半は理解度に合わせて進めます。'], ['04', 'アーカイブで復習', '授業後も講義部分を繰り返し視聴できます。']];
const ReviewSlider = dynamic(() => import('../components/ReviewSlider'), { ssr: false, loading: () => <div>口コミを読み込み中…</div> });
const reviews = [
  { grade: '既卒生', gender: '男', nickname: 'Nさん', icon: '/images/parent_icon_dog.webp', comment: '夏から始めたんですが、わずか３か月で模試の地理が60点台→80点台に！先生が「得点に直結する考え方」だけを選んで教えてくださるので、効率が抜群でした。他の科目に時間を回せたのもありがたかったです。' },
  { grade: '高3', gender: '女', nickname: 'Hさん', icon: '/images/parent_icon_flower.webp', comment: '理系科目中心の学習スケジュールの中で、地理を最小限の時間で仕上げたいと思って受講しました。結果、共通テスト本番では85点を取ることができ、合否にも大きく影響しました。' },
  { grade: '高3', gender: '男', nickname: 'Tさん', icon: '/images/parent_icon_brother.webp', comment: '実際に学校で地理を教えている先生という点に惹かれました。授業内容が「テストでどう出るか」を踏まえていて、保護者としても安心して任せられます。' },
  { grade: '高2', gender: '女', nickname: 'Sさん', icon: '/images/parent_icon_user.jpg', comment: 'オンライン授業に不安がありましたが、生徒一人ひとりの理解度を見ながら進めてくれるので安心でした。質問しやすい雰囲気です。' },
  { grade: '高2', gender: '男', nickname: 'Aさん', icon: '/images/parent_icon_user.jpg', comment: '定期試験前には個別に質問対応してくださり、苦手分野をしっかりフォローしてくれました。' },
];

export default function MiyazakiOnlinePage() {
  return <>
    <Head><title>宮崎県の中学生に、遠回りしない勉強を｜学習塾RAPID</title><meta name="description" content="宮崎県の中学生のために、教育のプロが学習を個別最適化。塾長が直接指導し、必要な時だけ1コマから受講できるオンライン個別指導です。" /><link rel="icon" href="/images/アイコン　文字なし.png" /><link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" /><link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@500;700;900&family=Zen+Kaku+Gothic+New:wght@500;700;900&display=swap" rel="stylesheet" /></Head>
    <div className={styles.page}>
      <header className={styles.header}><a href="#top" className={styles.brand} aria-label="学習塾RAPID トップ"><Image src="/images/アイコン　文字あり.webp" alt="学習塾RAPID" width={140} height={36} className={styles.brandLogoImg} /><span className={styles.brandNameText}>学習塾RAPID</span></a><nav className={styles.nav} aria-label="ページ内ナビゲーション"><a href="#pillars">3つの強み</a><a href="#lesson">授業の仕組み</a><a href="#flow">受講の流れ</a><a href="#price">料金</a><a href="#profile">塾長紹介</a></nav><a className={styles.headerLine} href={LINE_URL} target="_blank" rel="noopener noreferrer"><IconLine /><span>公式LINEで相談</span></a></header>
      <main id="top">
        <section className={styles.heroRestore}><div className={styles.heroBgWrapper}><Image src="/images/center.jpeg" alt="集中して勉強に取り組む中学生" fill priority className={styles.heroBgImage} sizes="100vw" /><div className={styles.heroOverlay} /></div><div className={styles.heroContainer}><div className={styles.heroContent}><div className={styles.eyebrowBadge}><Image src="/images/アイコン　文字なし.png" alt="" width={20} height={20} /><span>宮崎県の中学生限定 ・ 毎月10名様枠</span></div><h1 className={styles.heroTitle}>塾に毎週通うほどではない。<br />でも、独学だけでは不安。<br /><span className={styles.heroHighlight}>そんなときの「駆け込み寺」</span></h1><p className={styles.heroLead}>普段は自習でがんばるあなたを支えるオンライン指導。<br /><strong>「わからない！」と思ったその時に、必要な分だけ。</strong><br />教育のプロ（塾長）にマンツーマンで相談できる安心のサポート体制です。</p><div className={styles.heroPriceCard}><div className={styles.priceTag}>初回限定</div><div className={styles.priceBody}><span className={styles.priceDuration}>50分プロ個別指導</span><strong className={styles.priceAmount}>2,500<small>円(税込)</small></strong></div></div><div className={styles.heroMetaBadges}><span>入会金 0円</span><span>月額固定費 0円</span><span>1コマ〜都度受講</span><span>5教科対応</span></div><div className={styles.heroCtaArea}><LineCta>初回体験指導をLINEで申し込む</LineCta><p className={styles.heroSubText}>※一人ひとりの教材を分析・事前準備するため、毎月10名様限定です</p></div></div><div className={styles.heroVisualCardsWrap}><div className={styles.heroVisualCardGrid}><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/student teacher.jpeg" alt="プロ講師による完全マンツーマン指導" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>完全対話指導</span></div><div className={styles.cardTextContent}><h3>プロのマンツーマン</h3><p>教育を修めた塾長が質問に直接回答。</p></div></div><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/classroom.webp" alt="学校の教材そのままで指導" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>教材そのままOK</span></div><div className={styles.cardTextContent}><h3>いつものワークでOK</h3><p>学校の教材をそのまま使えます。</p></div></div><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/宮崎県.png" alt="宮崎県の中学生に寄り添う指導" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>地域密着型</span></div><div className={styles.cardTextContent}><h3>宮崎県の中学生限定</h3><p>地域の学習事情に寄り添います。</p></div></div></div></div></div></section>
        <section className={styles.heroSection}><div className={styles.heroBgWrapper}><Image src="/images/center.jpeg" alt="集中して勉強に取り組む中学生" fill priority className={styles.heroBgImage} sizes="100vw" /><div className={styles.heroOverlay} /></div><div className={styles.heroContainer}><div className={styles.heroContent}><div className={styles.eyebrowBadge}><Image src="/images/アイコン　文字なし.png" alt="" width={20} height={20} /><span>宮崎県の中学生のための個別指導</span></div><h1 className={styles.heroTitle}>あなたに必要な勉強を。<br /><span className={styles.heroHighlight}>あなたに合った方法で。</span></h1><p className={styles.heroLead}>頑張っているのに伸びない。<br />それは勉強時間ではなく、<strong>自分に合った学び方</strong>が見つかっていないからかもしれません。</p><p className={styles.heroSupport}>宮崎県の出題傾向と一人ひとりの理解度をもとに、教育のプロが最短距離の学び方を考えます。必要な時だけ、1コマから受講できます。</p><div className={styles.heroMetaBadges}><span>塾長が直接指導</span><span>過去問10年分析</span><span>1コマから</span><span>5教科対応</span></div><div className={styles.heroCtaArea}><LineCta /><p className={styles.heroSubText}>まずは、お子さまの学習状況をお聞かせください</p></div></div><div className={styles.heroVisualCardsWrap}><div className={styles.heroVisualCardGrid}><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/teacher mae.jpg" alt="塾長が直接指導" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>人</span></div><div className={styles.cardTextContent}><h3>塾長が直接指導</h3><p>担当講師が変わらず、一貫した指導。</p></div></div><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/宮崎県.png" alt="宮崎県の出題傾向を分析" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>戦略</span></div><div className={styles.cardTextContent}><h3>宮崎県に特化</h3><p>過去問10年分から優先順位を設計。</p></div></div><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/using pc.jpg" alt="授業後も学べるアーカイブ" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>仕組み</span></div><div className={styles.cardTextContent}><h3>学びが残る</h3><p>1コマの授業を、復習資産に。</p></div></div></div></div></div></section>
        <section id="pillars" className={styles.pillarSection}><div className={styles.sectionInner}><div className={styles.sectionHeader}><span className={styles.sectionSubTitle}>RAPID METHOD</span><h2>最短距離の学びをつくる、3つの仕組み。</h2><p>「誰が」「何を」「どう定着させるか」を、一人ひとりに合わせて設計します。</p></div><div className={styles.pillarGrid}>{pillars.map(([num, type, title, copy]) => <article className={styles.pillarCard} key={num}><span className={styles.pillarNum}>{num}</span><span className={styles.pillarType}>{type}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
        <section className={styles.directSection}><div className={styles.sectionInner}><div className={styles.directGrid}><div className={styles.directMainCard}><span className={styles.directBadge}>01 · PERSON</span><h2>すべての生徒を、塾長が直接指導します。</h2><p className={styles.directCopy}>誰に教わるかが最初から明確だから、毎回違う先生になったり、指導品質にばらつきが出たりしません。教育を専門的に学び、現役教師でもある塾長が、理解の深まりまで一貫して見届けます。</p><div className={styles.reasonPills}><span>担当講師が変わらない</span><span>理解度を継続して把握</span><span>一貫した指導品質</span></div></div><div className={styles.directPortrait}><Image src="/images/principal.png" alt="学習塾RAPID 塾長" width={380} height={480} className={styles.profileImg} /></div></div></div></section>
        <section className={styles.strategySection}><div className={styles.sectionInner}><div className={styles.sectionHeader}><span className={styles.sectionSubTitle}>02 · STRATEGY</span><h2>全国共通の勉強ではなく、<br />宮崎県で結果を出す勉強を。</h2><p>教育を専門的に学んだ塾長が、宮崎県の傾向と生徒の理解度から学び方を設計します。</p></div><div className={styles.strategyProfileGrid}><div><div className={styles.strategyFlow}><div><b>01</b><strong>宮崎県過去問10年分析</strong><span>出題傾向・頻出分野を把握</span></div><i>↓</i><div><b>02</b><strong>理解度・特性を確認</strong><span>どこでつまずいているかを見つける</span></div><i>↓</i><div><b>03</b><strong>優先順位を決定</strong><span>何から、どこに時間を使うかを整理</span></div><i>↓</i><div className={styles.strategyResult}><b>04</b><strong>指導方法を個別最適化</strong><span>無駄な遠回りを減らし、伸びる学び方へ</span></div></div><div className={styles.strategyCallout}><strong>何を勉強するかだけではありません。</strong><br />何から始めるか。どの方法なら理解できるか。そこまで含めて考えます。</div></div></div></div></section>
        <section id="lesson" className={styles.lessonSection}><div className={styles.sectionInner}><div className={styles.sectionHeader}><span className={styles.sectionSubTitle}>03 · EXPERIENCE</span><h2>50分間、一方的に教えて終わりではありません。</h2><p>全員に同じ50分を提供せず、理解度に合わせて後半の内容が変わります。</p></div><div className={styles.lessonTimeline}><div className={styles.lessonStart}><strong>前半：講義・解説</strong><p>自分だけのためにカスタマイズされたオリジナル解説授業</p></div><div className={styles.lessonBranches}><div className={styles.lessonBranchHeading}>後半：理解度を確認</div><article><span>A</span><h3>自分で解説してみる</h3><p>自分の言葉で説明し、本当に理解できているか確認。</p></article><article><span>B</span><h3>追加質問</h3><p>分からない部分を残さず、さらに質問。</p></article><article><span>C</span><h3>類題チャレンジ</h3><p>「分かった」を「自分で解ける」に変える。</p></article></div><div className={styles.lessonArrow}>講義開設後、理解度に応じて指導方法が個別に分岐します</div></div></div></section>
        <section className={styles.archiveSection}><div className={styles.sectionInner}><div className={styles.archiveHeading}><span className={styles.sectionSubTitle}>LEARNING LIBRARY</span><h2>授業は50分。<br /><span>学びは、その後も続きます。</span></h2><p>単発なのに、受講した1コマがその月の学習資産になる。</p></div><div className={styles.archiveGrid}><article><span>01</span><h3>自分の授業を復習</h3><p>受講後1か月間、自分が受けた講義部分を何度でも視聴できます。一度で理解できなくても、何度でも戻れます。</p></article><article><span>02</span><h3>他の授業も学べる</h3><p>受講月は、宮崎県の頻出問題・難関問題・つまずきやすい問題など、他の講義部分も視聴できます。</p></article></div></div></section>
        <section className={styles.worrySection}><div className={styles.sectionInner}><div className={styles.sectionHeader}><span className={styles.sectionSubTitle}>LEARNING REFUGE</span><h2>こんなとき、一人で悩んでいませんか？</h2><p>高品質な個別最適化指導を、必要なタイミングで。</p></div><div className={styles.sceneGrid}>{worries.map((worry, index) => <div className={styles.worryCard} key={worry}><CheckIcon /><span>{worry}</span><small>SCENE 0{index + 1}</small></div>)}</div><div className={styles.templeBanner}><div className={styles.templeInner}><Image src="/images/アイコン　文字なし.png" alt="" width={48} height={48} /><div><p className={styles.templeKicker}>宮崎県の中学生の学習の駆け込み寺</p><h3 className={styles.templeTitle}>毎週通わせる塾ではなく、<strong>困ったときの「駆け込み寺」</strong>です。</h3></div></div></div></div></section>
        <section id="flow" className={styles.flowSection}><div className={styles.sectionInner}><div className={styles.sectionHeader}><span className={styles.sectionSubTitle}>SIMPLE 4 STEPS</span><h2>受講までの流れ</h2></div><div className={styles.flowGrid}>{flowSteps.map(([num, title, text]) => <article className={styles.flowCard} key={num}><StepIcon step={num} /><span className={styles.flowStepBadge}>STEP {num}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
        <section className={styles.startupSection}><div className={styles.sectionInner}><div className={styles.startupCard}><span className={styles.sectionSubTitle}>LIMITED STUDENTS</span><h2>一人ひとりの学習に向き合うため、<br />募集人数には限りがあります。</h2><p>宮崎県で学習塾を立ち上げた現在、塾長が直接対応できる範囲でオンライン受講生を募集しています。全員の学習内容を把握し、授業の準備に時間をかけるための人数設定です。</p></div></div></section>
        <section id="price" className={styles.priceSection}><div className={styles.sectionInner}><div className={styles.sectionHeader}><span className={styles.sectionSubTitle}>STARTUP PRICING</span><h2>宮崎での新しい挑戦を、<br />今だけスタートアップ価格で。</h2><p>価値を知っていただくための、開校初期の料金です。</p></div><div className={styles.priceGrid}><div className={`${styles.priceCard} ${styles.priceTrial}`}><span className={styles.priceBadge}>初回</span><h3>50分 個別指導</h3><div className={styles.priceVal}><strong>2,500</strong><span>円（税込）</span></div></div><div className={`${styles.priceCard} ${styles.priceRegular}`}><span className={`${styles.priceBadge} ${styles.priceBadgeMain}`}>継続</span><h3>50分 個別指導</h3><div className={styles.priceVal}><strong>3,500</strong><span>円（税込）</span></div></div></div><div className={styles.priceFeatureRow}><span>入会金なし</span><span>月額固定なし</span><span>1コマから</span><span>中学生5教科対応</span></div></div></section>
        <section className={styles.finalCtaSection}><div className={styles.finalCtaBg}><Image src="/images/using pc.jpg" alt="オンライン学習風景" fill className={styles.finalCtaImg} /><div className={styles.finalCtaOverlay} /></div><div className={styles.finalCtaContent}><h2>あなたに必要な勉強を。<br />必要なタイミングで。</h2><p>塾長が直接指導し、宮崎県特化の戦略で学び方を個別最適化。理解度に合わせた50分とアーカイブで、授業後の学びまで支えます。</p><div className={styles.finalCtaButtonWrap}><LineCta /></div><small className={styles.finalLimitNotice}>初回指導について、公式LINEからお気軽にご相談ください</small></div></section>
        <section className={styles.personMerged} id="person"><div className={styles.sectionInner}><div className={styles.personMergedHeading}><span className={styles.sectionSubTitle}>01 · PERSON</span><h2>すべての生徒を、塾長が直接指導します。</h2><p>誰に教わるかが最初から明確だから、理解の深まりまで一貫して見届けます。</p></div><div className={styles.personMergedGrid}><div className={styles.personMergedPhoto}><Image src="/images/principal.png" alt="学習塾RAPID 塾長" width={380} height={480} className={styles.profileImg} /></div><div className={styles.personMergedBody}><p>教育を専門的に学び、現役教師でもある塾長が、すべての生徒を直接担当します。毎回違う先生になったり、指導品質にばらつきが出たりしない、一貫した個別指導です。</p><div className={styles.reasonPills}><span>担当講師が変わらない</span><span>理解度を継続して把握</span><span>一貫した指導品質</span></div><div className={styles.careerBox}><h3>塾長の略歴</h3><ul><li>五ヶ瀬中等教育学校 卒業</li><li>広島大学 教育学部 卒業</li><li>広島大学大学院 教育学研究科 修了</li><li>現役教師</li></ul></div></div></div></div></section>
        <section className={styles.reviewsSection}><div className={styles.sectionInner}><div className={styles.sectionHeader}><span className={styles.sectionSubTitle}>STUDENT VOICES</span><h2>実際に受講した方の口コミ</h2><p>一人ひとりに合わせた指導について、受講生・保護者の声をご紹介します。</p></div><div className={styles.reviewSliderFrame}><ReviewSlider reviews={reviews} interval={4000} /></div></div></section>
      </main>
      <footer className={styles.footer}><div className={styles.footerInner}><div className={styles.footerBrand}><Image src="/images/アイコン　文字あり.webp" alt="学習塾RAPID" width={130} height={34} /></div><div className={styles.footerLinks}><a href={LINE_URL} target="_blank" rel="noopener noreferrer">公式LINEで質問・相談</a></div><small className={styles.copyright}>© {new Date().getFullYear()} 学習塾 RAPID All rights reserved.</small></div></footer>
    </div>
  </>;
}
