import Head from 'next/head';
import Image from 'next/image';
import dynamic from 'next/dynamic';
import styles from '../src/styles/miyazaki-online.module.css';
import SectionTitle from '../components/SectionTitle';

const LINE_URL = 'https://lin.ee/Nwh2C8u';
const experienceVideoId = '3JZ_D3ELwOQ';
function IconLine() { return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 4C6.9 4 3 7.3 3 11.4c0 3.6 3.1 6.6 7.4 7.2-.3 1-.2 1.9-.1 2.5.1.4.4.5.7.3.5-.3 2.4-1.6 3.6-2.6 5-.4 8.4-3.5 8.4-7.4C23 7.3 17.1 4 12 4z" fill="currentColor" /></svg>; }
function CheckIcon() { return <svg className={styles.checkIcon} width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="2" /><path d="m8 12 2.5 2.5L16 9" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function StepIcon({ step }) { const paths = { '01': <><rect x="5" y="4" width="14" height="16" rx="2" /><path d="M8 8h8M8 12h5M8 16h8" /></>, '02': <><circle cx="10" cy="10" r="5" /><path d="m14 14 5 5M8 10h4M10 8v4" /></>, '03': <><path d="M5 5h14v10H5z" /><path d="M9 20h6M12 15v5" /></>, '04': <><path d="M6 5h12v14H6z" /><path d="m9 12 2 2 4-5" /></> }; return <svg className={styles.stepIcon} viewBox="0 0 24 24" fill="none" aria-hidden="true">{paths[step]}</svg>; }
function LineCta({ children = '初回指導について相談する' }) { return <a className={styles.cta} href={LINE_URL} target="_blank" rel="noopener noreferrer"><IconLine />{children}</a>; }

const pillars = [
  { num: '01', label: '誰が', title: '塾長が直接指導', copy: '誰に教わるかが、最初から決まっています。', points: ['担当講師が変わらない', '理解度を継続して把握'], href: '#person' },
  { num: '02', label: '何を', title: '宮崎県特化の戦略', copy: '宮崎県を知るから、遠回りさせない。', points: ['過去問10年分の出題傾向を分析', '理解度から学ぶ優先順位を決定'], href: '#strategy' },
  { num: '03', label: 'どう定着させるか', title: '個別最適化 × アーカイブ', copy: '単発なのに、学びが残る。', points: ['受講後1か月、講義を何度でも見返せる', '受講月は他の講義も視聴できる'], href: '#archive' },
];
const singleSessionTags = ['最低受講回数なし', '月額定期受講なし', '入会金0円'];
const singleSessionSteps = [['1', 'LINEで依頼', '指導3日前までに、教えてほしい内容を送るだけ。'], ['2', '50分の個別指導', '料金は1コマ単位。月額の固定費はかかりません。'], ['3', 'また必要な時に', '最低受講回数なし。次に受けるかは毎回自由です。']];
const learningCycle = [['01', '授業', '50分の個別指導', '前半は講義、後半は理解度に合わせて確認・演習。'], ['02', '復習', 'アーカイブで復習', '自分の講義を、受講後1か月何度でも。'], ['03', '応用', 'ほかの講義で応用', '頻出・難関・つまずき問題の講義も視聴できる。']];
// Learning cycle ring: each segment is one arrow (bar + head) cut out with clip-path.
// The ring is drawn already projected onto a tilted floor: coordinates are % of the
// (squashed) plane, the band is thicker at the front, and the back is slightly narrower.
// Angles start at 12 o'clock (the back) and run clockwise.
const CYCLE_BAND_BACK = 0.1;
const CYCLE_BAND_FRONT = 0.19;
const CYCLE_PERSPECTIVE = 0.06;
const CYCLE_HEAD = 6;
const CYCLE_GAP = 6;
const cycleSegmentColors = ['#fdba74', '#fb8a4c', '#ea580c'];
const cycleBand = (rad) => CYCLE_BAND_BACK + ((CYCLE_BAND_FRONT - CYCLE_BAND_BACK) * (1 - Math.cos(rad))) / 2;
// position: 0 = outer edge, .5 = band centre, 1 = inner edge.
function cyclePosition(angle, position) {
  const rad = (angle * Math.PI) / 180;
  const radius = 1 - cycleBand(rad) * position;
  const narrow = 1 - CYCLE_PERSPECTIVE * Math.cos(rad);
  return [50 + 50 * radius * narrow * Math.sin(rad), 50 - 50 * radius * Math.cos(rad)];
}
const cyclePoint = (angle, position) => cyclePosition(angle, position).map((value) => `${value.toFixed(2)}%`).join(' ');
function cycleSegmentPath(index, count) {
  const span = 360 / count;
  const start = index * span - span / 2 + CYCLE_GAP / 2;
  const end = start + span - CYCLE_GAP;
  const arc = (from, to, position) => {
    const steps = Math.ceil(Math.abs(to - from) / 3);
    return Array.from({ length: steps + 1 }, (_, i) => cyclePoint(from + ((to - from) * i) / steps, position));
  };
  return `polygon(${[...arc(start, end, 0), cyclePoint(end + CYCLE_HEAD, .5), ...arc(end, start, 1), cyclePoint(start + CYCLE_HEAD, .5)].join(', ')})`;
}
function cycleNodeStyle(index, count) {
  const [left, top] = cyclePosition((360 / count) * index, .5);
  return { left: `${left.toFixed(2)}%`, top: `${top.toFixed(2)}%` };
}
const strategySteps = [['01', '過去問10年分を分析', '宮崎県高校入試の出題傾向・頻出分野を把握。'], ['02', '理解度・特性を確認', 'どこでつまずいているかを見つける。'], ['03', '優先順位を決定', '何から、どこに時間を使うかを整理。'], ['04', '指導方法を個別最適化', '無駄な遠回りを減らし、伸びる学び方へ。']];
const scenes = ['テスト前だけ相談したい', '苦手単元だけ克服したい', '学校のワークが分からない', '高校受験前に対策したい', '普段は自分で勉強したい', '単発の問題を解決したい'];
const worries = [
  '定期テスト前だけ、集中して質問できる先生がほしい',
  '苦手な単元だけを短期間で克服したい',
  '塾に毎週通うほどではないけれど、独学だけでは不安',
];
const flowSteps = [['01', '教えてほしい内容を送る', '指導3日前までに教材・問題・苦手な内容をLINEで送信。'], ['02', '塾長が内容を確認', '教材と質問内容を読み込み、必要な授業を準備。'], ['03', '50分の個別指導', '前半は講義、後半は理解度に合わせて進めます。'], ['04', 'アーカイブで復習', '授業後も講義部分を繰り返し視聴できます。']];
const ReviewSlider = dynamic(() => import('../components/ReviewSlider'), { ssr: false, loading: () => <div>口コミを読み込み中…</div> });
const reviews = [
  { grade: '既卒生', gender: '男', nickname: 'Nさん', icon: '/images/parent_icon_dog.webp', comment: '夏から始めたんですが、わずか３か月で模試の地理が60点台→80点台に！先生が「得点に直結する考え方」だけを選んで教えてくださるので、効率が抜群でした。他の科目に時間を回せたのもありがたかったです。' },
  { grade: '高3', gender: '女', nickname: 'Hさん', icon: '/images/parent_icon_flower.webp', comment: '理系科目中心の学習スケジュールの中で、地理を最小限の時間で仕上げたいと思って受講しました。結果、共通テスト本番では85点を取ることができ、合否にも大きく影響しました。' },
  { grade: '高3', gender: '男', nickname: 'Tさん', icon: '/images/parent_icon_brother.webp', comment: '実際に学校で地理を教えている先生という点に惹かれました。授業内容が「テストでどう出るか」を踏まえていて、保護者としても安心して任せられます。' },
  { grade: '高2', gender: '女', nickname: 'Sさん', icon: '/images/parent_icon_user.jpg', comment: 'オンライン授業に不安がありましたが、生徒一人ひとりの理解度を見ながら進めてくれるので安心でした。質問しやすい雰囲気です。' },
  { grade: '高2', gender: '男', nickname: 'Aさん', icon: '/images/parent_icon_user.jpg', comment: '定期試験前には個別に質問対応してくださり、苦手分野をしっかりフォローしてくれました。' },
];

export default function MiyazakiOnlinePage() {
  return <>
    <Head><title>宮崎県の中学生に、遠回りしない勉強を｜学習塾RAPID</title><meta name="description" content="宮崎県の中学生のために、教育のプロが学習を個別最適化。塾長が直接指導し、必要な時だけ1コマから受講できるオンライン個別指導です。" /><link rel="icon" href="/images/アイコン　文字なし.png" /><link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" /><link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@500;700;900&family=Zen+Kaku+Gothic+New:wght@500;700;900&display=swap" rel="stylesheet" /></Head>
    <div className={styles.page}>
      <header className={styles.header}><a href="#top" className={styles.brand} aria-label="学習塾RAPID トップ"><Image src="/images/アイコン　文字あり.webp" alt="学習塾RAPID" width={140} height={36} className={styles.brandLogoImg} /><span className={styles.brandNameText}>学習塾RAPID</span></a><nav className={styles.nav} aria-label="ページ内ナビゲーション"><a href="#pillars">3つの強み</a><a href="#lesson">授業の仕組み</a><a href="#flow">受講の流れ</a><a href="#price">料金</a><a href="#profile">塾長紹介</a></nav><a className={styles.headerLine} href={LINE_URL} target="_blank" rel="noopener noreferrer"><IconLine /><span>公式LINEで相談</span></a></header>
      <main id="top">
        <section className={styles.heroRestore}><div className={styles.heroBgWrapper}><Image src="/images/center.jpeg" alt="集中して勉強に取り組む中学生" fill priority className={styles.heroBgImage} sizes="100vw" /><div className={styles.heroOverlay} /></div><div className={styles.heroContainer}><div className={styles.heroContent}><div className={styles.eyebrowBadge}><Image src="/images/アイコン　文字なし.png" alt="" width={20} height={20} /><span>宮崎県の中学生対象・毎月10名限定</span></div><h1 className={styles.heroTitle}>塾に毎週通うほどではない。<br />でも、独学だけでは不安。<br /><span className={styles.heroHighlight}>そんなときの「駆け込み寺」</span></h1><p className={styles.heroLead}>普段は自習でがんばるあなたを支えるオンライン指導。<br /><strong>「わからない！」と思ったその時に、必要な分だけ。</strong><br />教育のプロ（塾長）にマンツーマンで相談できる安心のサポート体制です。</p><div className={styles.heroPriceCard}><div className={styles.priceTag}>初回限定</div><div className={styles.priceBody}><span className={styles.priceDuration}>50分プロ個別指導</span><strong className={styles.priceAmount}>2,500<small>円(税込)</small></strong></div></div><div className={styles.heroMetaBadges}><span>入会金 0円</span><span>月額固定費 0円</span><span>1コマ〜都度受講</span><span>5教科対応</span></div><div className={styles.heroCtaArea}><LineCta>初回体験指導をLINEで申し込む</LineCta><p className={styles.heroSubText}>※一人ひとりの教材を分析・事前準備するため、毎月10名様限定です</p></div></div><div className={styles.heroVisualCardsWrap}><div className={styles.heroVisualCardGrid}><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/student teacher.jpeg" alt="プロ講師による完全マンツーマン指導" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>完全対話指導</span></div><div className={styles.cardTextContent}><h3>プロのマンツーマン</h3><p>教育理論を研究してきた塾長が質問に直接回答</p></div></div><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/classroom.webp" alt="学校の教材そのままで指導" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>教材そのままOK</span></div><div className={styles.cardTextContent}><h3>いつものワークでOK</h3><p>学校の教材をそのまま使えます。</p></div></div><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/宮崎県.png" alt="宮崎県の中学生に寄り添う指導" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>地域密着型</span></div><div className={styles.cardTextContent}><h3>宮崎県の中学生限定</h3><p>宮崎県高校入試の出題傾向を踏まえた指導</p></div></div></div></div></div></section>
        <section className={styles.heroSection}><div className={styles.heroBgWrapper}><Image src="/images/center.jpeg" alt="集中して勉強に取り組む中学生" fill priority className={styles.heroBgImage} sizes="100vw" /><div className={styles.heroOverlay} /></div><div className={styles.heroContainer}><div className={styles.heroContent}><div className={styles.eyebrowBadge}><Image src="/images/アイコン　文字なし.png" alt="" width={20} height={20} /><span>宮崎県の中学生のための個別指導</span></div><h1 className={styles.heroTitle}>あなたに必要な勉強を。<br /><span className={styles.heroHighlight}>あなたに合った方法で。</span></h1><p className={styles.heroLead}>頑張っているのに伸びない。<br />それは勉強時間ではなく、<strong>自分に合った学び方</strong>が見つかっていないからかもしれません。</p><p className={styles.heroSupport}>宮崎県の出題傾向と一人ひとりの理解度をもとに、教育のプロが最短距離の学び方を考えます。必要な時だけ、1コマから受講できます。</p><div className={styles.heroMetaBadges}><span>塾長が直接指導</span><span>過去問10年分析</span><span>1コマから</span><span>5教科対応</span></div><div className={styles.heroCtaArea}><LineCta /><p className={styles.heroSubText}>まずは、お子さまの学習状況をお聞かせください</p></div></div><div className={styles.heroVisualCardsWrap}><div className={styles.heroVisualCardGrid}><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/teacher mae.jpg" alt="塾長が直接指導" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>人</span></div><div className={styles.cardTextContent}><h3>塾長が直接指導</h3><p>担当講師が変わらず、一貫した指導。</p></div></div><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/宮崎県.png" alt="宮崎県の出題傾向を分析" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>戦略</span></div><div className={styles.cardTextContent}><h3>宮崎県に特化</h3><p>過去問10年分から優先順位を設計。</p></div></div><div className={styles.glassCardItem}><div className={styles.cardImageHeader}><Image src="/images/using pc.jpg" alt="授業後も学べるアーカイブ" width={240} height={160} className={styles.cardPhoto} /><span className={styles.photoCaption}>仕組み</span></div><div className={styles.cardTextContent}><h3>学びが残る</h3><p>1コマの授業を、復習資産に。</p></div></div></div></div></div></section>
        <section id="pillars" className={styles.pillarSection}><div className={styles.sectionInner}><SectionTitle className={styles.sectionHeader} kicker="宮崎の中学生のための、学習の駆け込み寺" title="最短距離の学びをつくる、3つの柱。" description="「誰が」「何を」「どう定着させるか」を、一人ひとりに合わせて設計します。" backdrop="PILLARS" backdropOpacity={0.05} colors={{ description: 'var(--text-muted)' }} /><div className={styles.pillarGrid}>{pillars.map(({ num, label, title, copy, points, href }) => <article className={styles.pillarCard} key={num}><div className={styles.pillarCardMeta}><span className={styles.pillarNum}>{num}</span><span className={styles.pillarType}>{label}</span></div><h3>{title}</h3><p>{copy}</p><ul className={styles.pillarPoints}>{points.map((point) => <li key={point}><CheckIcon />{point}</li>)}</ul><a className={styles.pillarLink} href={href}>詳しく見る<span aria-hidden="true">→</span></a></article>)}</div><div className={styles.pillarNote}><span className={styles.pillarNoteBadge}>単発受講OK</span><p className={styles.pillarNoteLead}>さらにこれらを、<strong>1コマからの単発受講</strong>でご提供します。</p><ul className={styles.pillarNoteTags}>{singleSessionTags.map((tag) => <li key={tag}><CheckIcon />{tag}</li>)}</ul><a className={styles.pillarNoteLink} href="#price">料金と受講方法を見る<span aria-hidden="true">→</span></a></div></div></section>
        <section className={styles.directSection}><div className={styles.sectionInner}><div className={styles.directGrid}><div className={styles.directMainCard}><SectionTitle className={styles.directTitle} kicker="01 · PERSON" title="すべての生徒を、塾長が直接指導します。" description="誰に教わるかが最初から明確だから、毎回違う先生になったり、指導品質にばらつきが出たりしません。教育を専門的に学び、現役教師でもある塾長が、理解の深まりまで一貫して見届けます。" backdrop="01 · PERSON" colors={{ accent: "#7c2d12", text: "var(--text-dark)" }} /><div className={styles.reasonPills}><span>担当講師が変わらない</span><span>理解度を継続して把握</span><span>一貫した指導品質</span></div></div><div className={styles.directPortrait}><Image src="/images/principal.png" alt="学習塾RAPID 塾長" width={380} height={480} className={styles.profileImg} /></div></div></div></section>
        <section id="strategy" className={styles.strategySection}><div className={styles.sectionInner}><SectionTitle className={styles.sectionHeader} kicker="02 · STRATEGY" title="宮崎県高校入試の出題傾向を踏まえた指導" description="教育理論を研究してきた塾長が、宮崎県の高校入試の傾向と生徒の理解度から学び方を設計します。" backdrop="02 · STRATEGY" colors={{ description: 'var(--text-muted)' }} /><div className={styles.strategyLayout}><figure className={styles.strategyVisual}><div className={styles.strategyVisualImage} role="img" aria-label="宮崎県高校入試の過去問を分析している机の上" /><figcaption className={styles.strategyStat}><span>宮崎県公立高校入試</span><strong>10<small>年分</small></strong><span>の過去問から、出題傾向を分析</span></figcaption></figure><ol className={styles.strategySteps}>{strategySteps.map(([num, title, text]) => <li key={num}><span className={styles.strategyStepNum}>{num}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div><div className={styles.strategyStatement}><p className={styles.strategyStatementLead}>何を勉強するかだけではありません。</p><p>何から始めるか。どの方法なら理解できるか。<br /><strong>そこまで含めて考えます。</strong></p></div></div></section>
        <section id="lesson" className={styles.lessonSection}><div className={styles.sectionInner}><SectionTitle className={styles.sectionHeader} kicker="03 · EXPERIENCE" title="50分間、一方的に教えて終わりではありません。" description="前半終了後、理解度に応じて後半の指導方法が変わります。" backdrop="03 · EXPERIENCE" /><div className={styles.lessonTimeline}><div className={styles.lessonStart}><strong>個別カスタマイズされたオリジナル解説授業</strong><div className={styles.lessonVideo}><iframe src={`https://www.youtube.com/embed/${experienceVideoId}`} title="個別指導の講義イメージ" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div></div><div className={styles.lessonBranches}><div className={styles.lessonBranchHeading}>理解度に応じた指導方法</div><article><span>A</span><div><h3>自分で解説してみる</h3><p>自分の言葉で説明し、本当に理解できているか確認。</p></div></article><article><span>B</span><div><h3>追加質問</h3><p>分からない部分を残さず、さらに質問。</p></div></article><article><span>C</span><div><h3>類題チャレンジ</h3><p>「分かった」を「自分で解ける」に変える。</p></div></article></div></div><div id="archive" className={styles.learningCycle}><SectionTitle className={styles.learningCycleHeading} titleAs="h3" kicker="LEARNING LIBRARY" title="授業は50分。学びは、その後も続きます。" description="単発なのに、受講した1コマがその月の学習資産になります。" colors={{ description: 'var(--text-muted)' }} /><div className={styles.cycleRing}><div className={styles.cyclePlane}><div className={styles.cycleRingStage} aria-hidden="true">{learningCycle.map(([num], index) => <span className={styles.cycleSegmentDepth} style={{ clipPath: cycleSegmentPath(index, learningCycle.length) }} key={`depth-${num}`} />)}{learningCycle.map(([num], index) => <span className={styles.cycleSegment} style={{ clipPath: cycleSegmentPath(index, learningCycle.length), background: cycleSegmentColors[index] }} key={num} />)}</div><div className={styles.cycleCenter}><Image src="/images/アイコン　文字なし.png" alt="" width={36} height={36} /><p>学びが、<br />回り続ける。</p></div><ol className={styles.cycleNodes}>{learningCycle.map(([num, tag, title, text], index) => <li className={styles.cycleNode} style={cycleNodeStyle(index, learningCycle.length)} key={num}><span className={styles.cycleNodeNum}>{num}<small>{tag}</small></span><h4>{title}</h4><p>{text}</p></li>)}</ol></div><ol className={styles.cycleNotes}>{learningCycle.map(([num, , title, text]) => <li key={num}><b>{num}</b><strong>{title}</strong><span>{text}</span></li>)}</ol></div></div></div></section>
        <section className={styles.worrySection}><div className={styles.sectionInner}><SectionTitle className={styles.sectionHeader} kicker="PROBLEM" title="こんなとき、一人で悩んでいませんか？" description="高品質な個別最適化指導を、必要なタイミングで。" backdrop="PROBLEM" /><div className={styles.sceneGrid}>{worries.map((worry, index) => <article className={styles.worryCard} key={worry}><span className={styles.worryIcon}><CheckIcon /></span><p>{worry}</p><small>SCENE 0{index + 1}</small></article>)}</div></div><div className={styles.problemResolve}><div className={styles.problemChevrons} aria-hidden="true"><span className={styles.problemChevron} /><span className={styles.problemChevron} /></div><div className={styles.templeBanner}><div className={styles.templeInner}><Image src="/images/アイコン　文字なし.png" alt="" width={48} height={48} /><div> <h3 className={styles.templeTitle}>そんな時は、<strong>学習塾RAPID</strong>にお任せください！</h3></div></div></div></div></section>
        <section id="flow" className={styles.flowSection}><div className={styles.sectionInner}><SectionTitle className={styles.sectionHeader} kicker="STEPS" title="受講までの流れ" backdrop="STEPS" /><div className={styles.flowGrid}>{flowSteps.map(([num, title, text]) => <article className={styles.flowCard} key={num}><StepIcon step={num} /><span className={styles.flowStepBadge}>STEP {num}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
        <section className={styles.startupSection}><div className={styles.sectionInner}><SectionTitle className={styles.startupCard} kicker="LIMITED STUDENTS" title={<>一人ひとりの学習に向き合うため、<br />募集人数には限りがあります。</>} description="宮崎県で学習塾を立ち上げた現在、塾長が直接対応できる範囲でオンライン受講生を募集しています。全員の学習内容を把握し、授業の準備に時間をかけるための人数設定です。" backdrop="LIMITED STUDENTS" colors={{ accent: "#fed7aa", text: "#ffffff" }} /></div></section>
        <section id="price" className={styles.priceSection}><div className={styles.sectionInner}><SectionTitle className={styles.sectionHeader} kicker="STARTUP PRICING" title={<>宮崎での新しい挑戦を、<br />今だけスタートアップ価格で。</>} description="価値を知っていただくための、開校初期の料金です。" backdrop="STARTUP PRICING" /><div className={styles.priceGrid}><div className={`${styles.priceCard} ${styles.priceTrial}`}><span className={styles.priceBadge}>初回</span><h3>50分 個別指導</h3><div className={styles.priceVal}><strong>2,500</strong><span>円（税込）</span></div></div><div className={`${styles.priceCard} ${styles.priceRegular}`}><span className={`${styles.priceBadge} ${styles.priceBadgeMain}`}>継続</span><h3>50分 個別指導</h3><div className={styles.priceVal}><strong>3,500</strong><span>円（税込）</span></div></div></div><div className={styles.singleSession}><div className={styles.singleSessionHead}><span className={styles.singleSessionBadge}>単発受講</span><h3>必要な時に、1コマから依頼できます。</h3><p>毎週の通塾や月額契約はありません。「テスト前だけ」「この単元だけ」など、困った時にその都度お申し込みください。</p></div><ol className={styles.singleSessionSteps}>{singleSessionSteps.map(([num, title, text]) => <li key={num}><b>{num}</b><strong>{title}</strong><span>{text}</span></li>)}</ol></div><div className={styles.priceFeatureRow}><span>入会金なし</span><span>月額固定なし</span><span>1コマから</span><span>中学生5教科対応</span></div></div></section>
        <section className={styles.finalCtaSection}><div className={styles.finalCtaBg}><Image src="/images/using pc.jpg" alt="オンライン学習風景" fill className={styles.finalCtaImg} /><div className={styles.finalCtaOverlay} /></div><div className={styles.finalCtaContent}><h2>あなたに必要な勉強を。<br />必要なタイミングで。</h2><p>塾長が直接指導し、宮崎県特化の戦略で学び方を個別最適化。理解度に合わせた50分とアーカイブで、授業後の学びまで支えます。</p><div className={styles.finalCtaButtonWrap}><LineCta /></div><small className={styles.finalLimitNotice}>初回指導について、公式LINEからお気軽にご相談ください</small></div></section>
        <section className={styles.personMerged} id="person"><div className={styles.sectionInner}><SectionTitle className={styles.personMergedHeading} kicker="01 · PERSON" title="すべての生徒を、塾長が直接指導します。" description="誰に教わるかが最初から明確だから、理解の深まりまで一貫して見届けます。" backdrop="01 · PERSON" /><div className={styles.personMergedGrid}><div className={styles.personMergedPhoto}><Image src="/images/principal.png" alt="学習塾RAPID 塾長" width={380} height={480} className={styles.profileImg} /></div><div className={styles.personMergedBody}><p>塾長の安藤です。この度、自分が育った宮崎に恩返しをしたい！という気持ちでこの塾を立ち上げました！大学院と学校現場で学んだ「自分から勉強する子どもの指導法」を取り入れた授業をしていきます。</p><div className={styles.careerBox}><h3>塾長安藤の略歴</h3><ul><li>五ヶ瀬中等教育学校 卒業</li><li>広島大学 教育学部 卒業</li><li>広島大学大学院 教育学研究科 修了</li><li>現役教師</li></ul></div></div></div></div></section>
        <section className={styles.reviewsSection}><div className={styles.sectionInner}><SectionTitle className={styles.sectionHeader} kicker="STUDENT VOICES" title="実際に受講した方の口コミ" description="一人ひとりに合わせた指導について、受講生・保護者の声をご紹介します。" backdrop="STUDENT VOICES" /><div className={styles.reviewSliderFrame}><ReviewSlider reviews={reviews} interval={4000} /></div></div></section>
      </main>
      <footer className={styles.footer}><div className={styles.footerInner}><div className={styles.footerBrand}><Image src="/images/アイコン　文字あり.webp" alt="学習塾RAPID" width={130} height={34} /></div><div className={styles.footerLinks}><a href={LINE_URL} target="_blank" rel="noopener noreferrer">公式LINEで質問・相談</a></div><small className={styles.copyright}>© {new Date().getFullYear()} 学習塾 RAPID All rights reserved.</small></div></footer>
    </div>
  </>;
}
